apiVersion: apps/v1
kind: Deployment
metadata:
  name: unity-java
spec:
  selector:
    matchLabels:
      app: unity-java
  template:
    metadata:
      labels:
        app: unity-java
    spec:
      containers:
      - name: unity-java
        image: 154100284802.dkr.ecr.us-east-1.amazonaws.com/UNITY-IMAGE:TAG
        ports:
        - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: unity-java-svc
spec:
  selector:
    app: unity-java
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
